### ISSUE TITLE
MySQL update query run on all front-end page loads

### ISSUE THREAD

**Issue by wpscholar** [newfold-labs/wp-module-onboarding#216]
![WP_Quick_Start_–_Hey_there_](https://user-images.githubusercontent.com/890951/232826977-73985464-e897-4d28-89d7-801ba3f5d90f.png)

We shouldn't be doing any writes to the database for a normal page load.

**Comment by wpscholar** [comment]
@abhijitb - I'm still seeing this happen on my wpquickst.art site with version 2.13.2 of the Bluehost plugin.

**Comment by abhijitb** [comment]
@wpscholar - Yes I was also able to replicate it on the current bluehost plugin version of 2.13.2 which has onboarding version 1.3.0 ... our latest release 1.4.0 fixes this issue

**Comment by abhijitb** [comment]
Onboarding version 1.4.1 is now live and the issue is fixed ... Closing this issue

**Comment by wpscholar** [comment]
@abhijitb This is still an issue. This is the line of code responsible: https://github.com/newfold-labs/wp-module-onboarding/blob/trunk/includes/ModuleController.php#L45
